# Generated by Django 6.0.7 on 2026-08-11 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('official_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quiz_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('vacancies', models.PositiveIntegerField(blank=True, null=True)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Application Open', 'Application Open'), ('Application Closed', 'Application Closed'), ('Exam Soon', 'Exam Soon'), ('Exam Completed', 'Exam Completed'), ('Result Released', 'Result Released')], default='Upcoming', max_length=50)),
                ('eligibility', models.TextField(blank=True)),
                ('syllabus', models.TextField(blank=True)),
                ('official_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Central', 'Central Government'), ('Telangana', 'Telangana Government')], default='Central', max_length=30)),
                ('category', models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Bank', 'Bank'), ('Police', 'Police'), ('Defence', 'Defence'), ('Teaching', 'Teaching'), ('PSU', 'PSU'), ('State PSC', 'State PSC'), ('High Court', 'High Court'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50)),
                ('state', models.CharField(default='All India', max_length=100)),
                ('location', models.CharField(default='All India', max_length=150)),
                ('qualification', models.CharField(max_length=200)),
                ('age_limit', models.CharField(default='18-35 Years', max_length=100)),
                ('vacancies', models.PositiveIntegerField(default=0)),
                ('salary', models.CharField(default='As Per Rules', max_length=100)),
                ('application_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20)),
                ('notification_date', models.DateField(default=django.utils.timezone.now)),
                ('last_date', models.DateField()),
                ('official_link', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('last_date', models.DateField()),
                ('official_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('result_date', models.DateField()),
                ('official_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Aptitude', 'Aptitude'), ('Reasoning', 'Reasoning'), ('English', 'English'), ('GK', 'General Knowledge'), ('Telangana GK', 'Telangana GK'), ('Computer', 'Computer Awareness')], max_length=50)),
                ('pdf', models.FileField(upload_to='study_materials/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=5)),
                ('message', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Acknowledged', max_length=20)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Bank', 'Bank'), ('Police', 'Police'), ('Defence', 'Defence'), ('Teaching', 'Teaching'), ('PSU', 'PSU'), ('State PSC', 'State PSC'), ('High Court', 'High Court'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_affairs', to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Bank', 'Bank'), ('Police', 'Police'), ('Defence', 'Defence'), ('Teaching', 'Teaching'), ('PSU', 'PSU'), ('State PSC', 'State PSC'), ('High Court', 'High Court'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50)),
                ('release_date', models.DateField()),
                ('official_link', models.URLField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Bank', 'Bank'), ('Police', 'Police'), ('Defence', 'Defence'), ('Teaching', 'Teaching'), ('PSU', 'PSU'), ('State PSC', 'State PSC'), ('High Court', 'High Court'), ('Health', 'Health'), ('Other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=20)),
                ('total_questions', models.PositiveIntegerField(default=20)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobportal.mocktest')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SSC', 'SSC'), ('UPSC', 'UPSC'), ('Railway', 'Railway'), ('Bank', 'Bank'), ('Police', 'Police'), ('Defence', 'Defence'), ('Teaching', 'Teaching'), ('PSU', 'PSU'), ('State PSC', 'State PSC'), ('High Court', 'High Court'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50)),
                ('year', models.IntegerField()),
                ('pdf_link', models.URLField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_papers', to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField(default=20)),
                ('attempted_date', models.DateField(auto_now_add=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Aptitude', 'Aptitude'), ('Reasoning', 'Reasoning'), ('English', 'English'), ('GK', 'General Knowledge'), ('Computer', 'Computer')], max_length=50)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.job')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_link', models.URLField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='jobportal.job')),
            ],
        ),
    ]
