# Generated by Django 6.0.7 on 2026-08-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouspaper',
            name='pdf_link',
            field=models.CharField(max_length=500),
        ),
    ]
