# Generated by Django 6.0.7 on 2026-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_alter_previouspaper_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffair',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
