# Generated by Django 6.0.7 on 2026-08-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_currentaffair_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='jobportal.exam'),
        ),
    ]
