# Generated by Django 6.0.7 on 2026-08-17 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_quizquestion_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(db_index=True, max_length=200)),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(default=60)),
                ('total_questions', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=50)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('unanswered', models.PositiveIntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='mocktest',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='mocktestquestion',
            name='mock_test',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='jobportal.exam'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='exam_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='is_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions_per_test',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_questions', to='jobportal.exam'),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='exam_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='subject',
            field=models.CharField(blank=True, choices=[('Aptitude', 'Aptitude'), ('Reasoning', 'Reasoning'), ('English', 'English'), ('General Knowledge', 'General Knowledge'), ('Current Affairs', 'Current Affairs'), ('Computer', 'Computer'), ('General Science', 'General Science'), ('Indian Polity', 'Indian Polity'), ('History', 'History'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Telangana GK', 'Telangana GK'), ('Law', 'Law'), ('Technical', 'Technical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='option1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='option2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='option3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='option4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mocktestquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['exam_name'], name='jobportal_m_exam_na_cfd7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['subject'], name='jobportal_m_subject_d4f8b5_idx'),
        ),
        migrations.AddField(
            model_name='dailymocktest',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_mock_tests', to='jobportal.exam'),
        ),
        migrations.AddField(
            model_name='dailymocktest',
            name='questions',
            field=models.ManyToManyField(related_name='daily_tests', to='jobportal.mocktestquestion'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='daily_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobportal.dailymocktest'),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailymocktest',
            constraint=models.UniqueConstraint(fields=('exam_name', 'test_date'), name='unique_daily_mock_per_exam'),
        ),
    ]
