# Generated by Django 6.0.7 on 2026-08-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_dailymocktest_mocktestattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Tough', 'Tough')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='source',
            field=models.CharField(blank=True, default='Practice', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportal.exam'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportal.job'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
