# Generated by Django 6.0.7 on 2026-09-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_quizquestion_difficulty_quizquestion_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestattempt',
            name='daily_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='jobportal.dailymocktest'),
        ),
    ]
