# Generated by Django 6.0.7 on 2026-09-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_quizquestionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattempt',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to='jobportal.exam'),
        ),
        migrations.AlterField(
            model_name='mocktestattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
